<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE food [
<!ELEMENT food(item)+>
<!ELEMENT item(name,description,price,type)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT type (#PCDATA)>
]>
<food>
	<item>
		<name>Fried Rice</name>
		<description>With chicken curry</description>
		<price currency= "LKR">Rs.300</price>
		<type> Full, budget pack</type>
	</item>
	
	<item>
		<name>Biryani </name>
		<description>With egg</description>
		<price currency= "LKR">Rs.250 </price>
		<type>Full,half, budget pack</type>
	</item>
</food>